#!/usr/bin/env php
<?php

use Merchnt\HAProxyManager\Command\ConfigurationManagerCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$application = new Application();

$application->addCommands([
    new ConfigurationManagerCommand()
]);

$application->run();